//ui
export const SET_EDITOR_STATUS = 'SET_EDITOR_STATUS'
export const SET_EDITOR_SCROLL_POSITION = 'SET_EDITOR_SCROLL_POSITION'

//data
export const SET_EDITOR_ARTICLE = 'SET_EDITOR_ARTICLE'
export const UPDATE_EDITOR_ARTICLE = 'UPDATE_EDITOR_ARTICLE'
