//Action types
export const SET_LOADING = 'SET_LOADING'
export const LOAD_JOB = 'LOAD_JOB'
export const SET_ATTRIBUTES = 'SET_ATTRIBUTES'
export const SET_SUBATTRIBUTES = 'SET_SUBATTRIBUTES'
export const SET_VARIABLES = 'SET_VARIABLES'
export const SET_TAGS = 'SET_TAGS'
export const SET_ICONS = 'SET_ICONS'
export const SET_NAMES = 'SET_NAMES'
export const SET_PATCH = 'SET_PATCH'
export const SET_PATCH_REF = 'SET_PATCH_REF'
export const SET_DEFAULT_BUILD = 'SET_DEFAULT_BUILD'
export const SET_BUILD_LIST = 'SET_BUILD_LIST'

export const SET_VIEW_MODE = 'SET_VIEW_MODE'
export const SET_VISIBILITY = 'SET_VISIBILITY'
export const SET_SEARCH_KEYWORD = 'SET_SEARCH_KEYWORD'
export const CLEAR_SEARCH_KEYWORD = 'CLEAR_SEARCH_KEYWORD'
export const SET_JOB = 'SET_JOB'
export const SELECT_SKILL = 'SELECT_SKILL'
export const SELECT_TREE = 'SELECT_TREE'
export const HOVER_NODE = 'HOVER_NODE'
export const SET_TAB = 'SET_TAB'

export const SET_LEVEL = 'SET_LEVEL'
export const SET_HLEVEL = 'SET_HLEVEL'
export const ADD_BUILD = 'ADD_BUILD'
export const REPLACE_BUILDS = 'REPLACE_BUILDS'
export const DELETE_BUILD = 'DELETE_BUILD'
export const RENAME_BUILD = 'RENAME_BUILD'

export const SET_STAT = 'SET_STAT'
export const SET_ELEMENT = 'SET_ELEMENT'
export const SET_WEAPON = 'SET_WEAPON'
export const SET_BRACELET = 'SET_BRACELET'
export const SET_BADGE = 'SET_BADGE'
export const SET_AMULET = 'SET_AMULET'
export const SET_SOULSHIELD = 'SET_SOULSHIELD'

export const SET_NODE = 'SET_NODE'

export const RESET_BUILD = 'RESET_BUILD'
