//ui
export const SKILL_UI_SET_CLASS = 'SKILL_UI_SET_CLASS'
export const SKILL_UI_SET_FILTER = 'SKILL_UI_SET_FILTER'
export const SKILL_UI_SET_SEARCH = 'SKILL_UI_SET_SEARCH'
export const SKILL_UI_SET_PATCH = 'SKILL_UI_SET_PATCH'
export const SKILL_UI_SET_CHARACTER_MODE = 'SKILL_UI_SET_CHARACTER_MODE'

//stat
export const SKILL_CHAR_SET_STAT = 'SKILL_CHAR_SET_STAT'
export const SKILL_CHAR_SET_ELEMENT_DMG = 'SKILL_CHAR_SET_ELEMENT_DMG'
export const SKILL_CHAR_SET_EQUIP = 'SKILL_CHAR_SET_EQUIP'

//data
export const SKILL_DATA_SET_CLASS_DATA = 'SKILL_DATA_SET_CLASS_DATA'
export const SKILL_DATA_SET_SKILL_PATCH_DATA = 'SKILL_DATA_SET_SKILL_PATCH_DATA'
export const SKILL_DATA_SET_BUILD_LIST = 'SKILL_DATA_SET_BUILD_LIST'
export const SKILL_DATA_SET_USER_BUILD_LIST = 'SKILL_DATA_SET_USER_BUILD_LIST'

//build
export const SKILL_BUILD_SET_ELEMENT = 'SKILL_DATA_SET_ELEMENT'
export const SKILL_BUILD_SET_SKILL = 'SKILL_BUILD_SET_SKILL'

//ref
export const SKILL_REF_SET_SKILL_NAMES = 'SKILL_REF_SET_SKILL_NAMES'
export const SKILL_REF_SET_PATCH_LIST = 'SKILL_REF_SET_PATCH_LIST'
