//ui
export const SET_TRANSLATOR_LANGUAGE = 'SET_TRANSLATOR_LANGUAGE'
export const SET_TRANSLATOR_NAMESPACE = 'SET_TRANSLATOR_NAMESPACE'
export const SET_TRANSLATOR_GROUP = 'SET_TRANSLATOR_GROUP'
export const SET_TRANSLATOR_LOADING = 'SET_TRANSLATOR_LOADING'
export const SET_TRANSLATOR_ERROR = 'SET_TRANSLATOR_ERROR'

//data
export const SET_TRANSLATOR_LANGUAGE_STATUS_DATA = 'SET_TRANSLATOR_LANGUAGE_STATUS_DATA'
export const SET_TRANSLATOR_LANGUAGE_STATUS = 'SET_TRANSLATOR_LANGUAGE_STATUS'
export const SET_TRANSLATOR_LANGUAGE_NAME = 'SET_TRANSLATOR_LANGUAGE_NAME'
export const SET_TRANSLATOR_LANGUAGE_DATA = 'SET_TRANSLATOR_LANGUAGE_DATA'
export const EDIT_TRANSLATOR_LANGUAGE_DATA = 'EDIT_TRANSLATOR_LANGUAGE_DATA'
export const PUSH_TRANSLATOR_LANGUAGE_DATA = 'PUSH_TRANSLATOR_LANGUAGE_DATA'
