//ui
export const SET_NAVBAR_MENU_STATUS = 'SET_NAVBAR_MENU_STATUS'
export const SET_NAVBAR_DROPDOWN_STATUS = 'SET_NAVBAR_DROPDOWN_STATUS'
export const SET_NAVBAR_DROPDOWN_POSITION = 'SET_NAVBAR_DROPDOWN_POSITION'
