//ui
export const SET_MARKET_SEARCH = 'SET_MARKET_SEARCH'
export const SET_MARKET_SUGGESTIONS = 'SET_MARKET_SUGGESTIONS'
export const SET_MARKET_BOOKMARKS = 'SET_MARKET_BOOKMARKS'
export const SET_MARKET_POPULAR_ITEMS = 'SET_MARKET_POPULAR_ITEMS'
export const SET_MARKET_GRAPH = 'SET_MARKET_GRAPH'
export const SET_MARKET_TERM = 'SET_MARKET_TERM'
export const SET_MARKET_GRAPH_INDICATOR = 'SET_MARKET_GRAPH_INDICATOR'
export const SET_MARKET_LAST_UPDATE = 'SET_MARKET_LAST_UPDATE'
export const SET_MARKET_LOADING = 'SET_MARKET_LOADING'

//item
export const SET_MARKET_DATA = 'SET_MARKET_DATA'
