export const GENERAL_SET_LANGUAGE = 'GENERAL_SET_LANGUAGE'
export const GENERAL_SET_USER = 'GENERAL_SET_USER'
export const GENERAL_SET_LOADING = 'GENERAL_SET_LOADING'
export const GENERAL_SET_INITIALIZED = 'GENERAL_SET_INITIALIZED'
